---

version: '3.8'

services:
  db:
    image: mysql:8.0.32
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ CMD, mysqladmin, ping, --silent ]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  db:
